### ISSUE TITLE
week 1

### ISSUE THREAD

**Issue by WilliamZ624** [RichardNeverGiveup/ECE651#1]
frontend local trial

**Comment by lifengyan-amber** [comment]
Week 1
Explore MySQL database set up + Azure web app set up

**Comment by 74751Spring** [comment]
Keep on learning Java, first time explore Springboot.

**Comment by llunga42** [comment]
learn the "React" and may create the framework.

**Comment by RichardNeverGiveup** [comment]
use servlet  JDBC build backend demo

**Comment by lifengyan-amber** [comment]
> Week 1 Explore MySQL database set up + Azure web app set up

MySQL Database connection detail:
Guide: 
https://docs.microsoft.com/en-us/azure/mysql/connect-workbench

Server name:
ece651group29.mysql.database.azure.com

Server admin login name:
group29admin@ece651group29

MySQL version:
8.0

password:
supersmart29!
